---
- name: Disable password login for user "ansible"
  hosts: all
  tasks:

    - name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
      blockinfile:
        path: /etc/ssh/sshd_config
        backup: yes
        block: |
          Match User ansible
          PasswordAuthentication no
      register: config_file

    - name: reload SSH daemon (if config file /etc/ssh/sshd_config was changed)
      service:
        name: sshd
        state: reloaded
      when: config_file.changed
