---
- name: Install latest verisons of already installed packages (updates) on target systems
  hosts: all
  tasks:
    - name: Step "apt update"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
#
    - name: Step "apt upgrade"
      apt:
        upgrade: safe
        dpkg_options: 'force-confold,force-confdef'
      become: yes
...